import { SeedPropertyDefinition } from './seedTypes'

// Auto-generated property definitions for all brand seeds
// Generated from analysis of all brand CSV files

export const BRAND_PROPERTY_DEFINITIONS: SeedPropertyDefinition[] = [
  { slug: 'collection', name: 'Коллекция' },
  { slug: 'style', name: 'Стиль' },
  { slug: 'product_type', name: 'Тип товара' },
  { slug: 'fixture_type', name: 'Тип светильника' },
  { slug: 'frame_material', name: 'Материал арматуры' },
  { slug: 'material', name: 'Материал' },
  { slug: 'body_material', name: 'Материал корпуса' },
  { slug: 'shade_material', name: 'Материал плафона' },
  { slug: 'decor_material', name: 'Материал декора' },
  { slug: 'base_material', name: 'Материал основания' },
  { slug: 'frame_color', name: 'Цвет арматуры', hasPhoto: true },
  { slug: 'color', name: 'Цвет', hasPhoto: true },
  { slug: 'body_color', name: 'Цвет корпуса', hasPhoto: true },
  { slug: 'shade_color', name: 'Цвет плафона', hasPhoto: true },
  { slug: 'decor_color', name: 'Цвет декора' },
  { slug: 'height', name: 'Высота' },
  { slug: 'height_mm', name: 'Высота, мм' },
  { slug: 'height_max_mm', name: 'Высота max, мм' },
  { slug: 'height_min_mm', name: 'Высота min, мм' },
  { slug: 'mounting_height_mm', name: 'Высота крепления, мм' },
  { slug: 'width', name: 'Ширина' },
  { slug: 'width_mm', name: 'Ширина, мм' },
  { slug: 'length', name: 'Длина' },
  { slug: 'length_mm', name: 'Длина, мм' },
  { slug: 'diameter', name: 'Диаметр' },
  { slug: 'diameter_mm', name: 'Диаметр, мм' },
  { slug: 'ceiling_cup_diameter', name: 'Диаметр потолочной чаши' },
  { slug: 'cutout_diameter', name: 'Диаметр врезного отверстия' },
  { slug: 'recessed_depth_mm', name: 'Глубина встройки, мм' },
  { slug: 'depth_mm', name: 'Глубина, мм' },
  { slug: 'weight_gross', name: 'Вес брутто' },
  { slug: 'weight_netto', name: 'Вес нетто' },
  { slug: 'weight_kg', name: 'Вес, кг' },
  { slug: 'packaging_height_cm', name: 'Высота упаковки, см' },
  { slug: 'packaging_length_cm', name: 'Длина упаковки, см' },
  { slug: 'packaging_width_cm', name: 'Ширина упаковки, см' },
  { slug: 'base_type', name: 'Тип цоколя' },
  { slug: 'lamp_count', name: 'Количество ламп' },
  { slug: 'lamp_power_w', name: 'Мощность лампы, W' },
  { slug: 'power_w', name: 'Мощность, Вт' },
  { slug: 'total_power_w', name: 'Общая мощность, W' },
  { slug: 'lamp_type', name: 'Тип лампы' },
  { slug: 'lamps_included', name: 'Лампы в комплекте' },
  { slug: 'built_in_led', name: 'Встроенные светодиоды' },
  { slug: 'led', name: 'LED' },
  { slug: 'light_source', name: 'Источник света' },
  { slug: 'luminous_flux', name: 'Световой поток' },
  { slug: 'luminous_flux_lm', name: 'Световой поток, лм' },
  { slug: 'color_temperature', name: 'Цветовая температура' },
  { slug: 'cri_index', name: 'Индекс цветопередачи (Ra)' },
  { slug: 'lighting_area_m2', name: 'Площадь освещения, м²' },
  { slug: 'voltage', name: 'Напряжение' },
  { slug: 'supply_voltage', name: 'Напряжение питания, В' },
  { slug: 'safety_class', name: 'Класс электробезопасности' },
  { slug: 'mains_frequency', name: 'Частота сети' },
  { slug: 'ip_rating', name: 'Степень защиты IP' },
  { slug: 'operating_temperature', name: 'Диапазон рабочих температур' },
  { slug: 'remote_control', name: 'Пульт ДУ' },
  { slug: 'dimmable', name: 'Диммирование' },
  { slug: 'switch', name: 'Выключатель' },
  { slug: 'motion_sensor', name: 'Датчик движения' },
  { slug: 'day_night_sensor', name: 'Датчик освещенности' },
  { slug: 'app_control', name: 'Управление через приложение' },
  { slug: 'touch_sensor', name: 'Touch сенсор' },
  { slug: 'mounting_type', name: 'Тип монтажа' },
  { slug: 'mounting_method', name: 'Способ монтажа' },
  { slug: 'mounting_fixture_type', name: 'Тип крепления' },
  { slug: 'mounting_location', name: 'Место монтажа' },
  { slug: 'fastening_type', name: 'Крепеж' },
  { slug: 'interior', name: 'Интерьер' },
  { slug: 'purpose', name: 'Назначение' },
  { slug: 'placement_zone', name: 'Зона размещения' },
  { slug: 'application_areas', name: 'Места применения' },
  { slug: 'shade_shape', name: 'Форма плафона' },
  { slug: 'diffuser_type', name: 'Вид рассеивателя' },
  { slug: 'shape', name: 'Форма' },
  { slug: 'warranty', name: 'Гарантия' },
  { slug: 'warranty_period', name: 'Гарантийный срок' },
  { slug: 'brand_country', name: 'Страна бренда' },
  { slug: 'country', name: 'Страна производства' },
  { slug: 'vendor_code', name: 'Артикул' },
  { slug: 'lamp_replaceable', name: 'Возможность замены ламп' },
  { slug: 'additional_lighting', name: 'Дополнительная подсветка' },
  { slug: 'additional_info', name: 'Дополнительные сведения' },
  { slug: 'accessories', name: 'Аксессуары' },
  { slug: 'swivel_mechanism', name: 'Поворотный механизм' },
  { slug: 'color_temp_adjustable', name: 'Изменение цветовой температуры' },
  { slug: 'height_adjustable', name: 'Регулировка по высоте' },
  { slug: 'stretch_ceiling_compatible', name: 'Для натяжных потолков' },
  { slug: 'power_supply', name: 'Блок питания' },
  { slug: 'cable_length', name: 'Длина провода' },
  { slug: 'cable_length_mm', name: 'Длина провода, мм' },
  { slug: 'chain_length', name: 'Длина цепи' },
  { slug: 'service_life', name: 'Срок службы' },
  { slug: 'led_service_life', name: 'Срок службы LED' },
  { slug: 'min_stock', name: 'Минимальный остаток' },
  { slug: 'availability_date', name: 'Дата поступления' },
  { slug: 'flicker_coefficient', name: 'Коэффициент пульсации' },
  { slug: 'ugr_rating', name: 'UGR (Unified Glare Rating)' },
  { slug: 'autonomous_operation_time', name: 'Время автономной работы, ч' },
  { slug: 'beam_angle', name: 'Угол рассеивания' },
  { slug: 'led_count', name: 'Количество светодиодов' },
  { slug: 'luminous_efficacy', name: 'Световая отдача' },
  { slug: 'connection_method', name: 'Способ подключения' },
  { slug: 'control_type', name: 'Тип управления' },
  { slug: 'packaging_volume_m3', name: 'Объем упаковки, м³' },
]

// Reverse mapping for property lookups
export const PROPERTY_SLUG_MAP: Record<string, string> = {
  'Коллекция': 'collection',
  'Серия': 'collection',
  'Подколлекция': 'subcollection',
  'Стиль': 'style',
  'Материал арматуры': 'frame_material',
  'Материал': 'material',
  'Материал корпуса': 'body_material',
  'Материал плафона': 'shade_material',
  'Материал плафонов': 'shade_material',
  'Материал декора': 'decor_material',
  'Mатериал': 'material',
  'Цвет арматуры': 'frame_color',
  'Цвет': 'color',
  'Цвет корпуса': 'body_color',
  'Цвет плафона': 'shade_color',
  'Цвет плафонов': 'shade_color',
  'Цвет светильника': 'body_color',
  'Цвет декора': 'decor_color',
  'Цвет основания': 'base_color',
  'Высота': 'height',
  'Высота, мм': 'height_mm',
  'Высота (H), мм': 'height_mm',
  'Высота (см)': 'height_cm',
  'Высота мм': 'height_mm',
  'Высота (H max), мм': 'height_max_mm',
  'Высота (H min), мм': 'height_min_mm',
  'Высота потолочной чаши/крепления, мм': 'mounting_height_mm',
  'Высота потолочной чаши мм': 'mounting_height_mm',
  'Высота плафона, мм': 'shade_height_mm',
  'Высота корпуса, см': 'body_height_cm',
  'Высота люстры с тросом': 'chandelier_height_with_cable',
  'Высота драйвера': 'driver_height',
  'Высота встройки': 'recessed_height',
  'Ширина': 'width',
  'Ширина, мм': 'width_mm',
  'Ширина (см)': 'width_cm',
  'Ширина мм': 'width_mm',
  'Длина': 'length',
  'Длина, мм': 'length_mm',
  'Длина (см)': 'length_cm',
  'Длина мм': 'length_mm',
  'Длина (Глубина) (L), мм': 'length_mm',
  'Длина на треке': 'track_length',
  'Диаметр': 'diameter',
  'Диаметр, мм': 'diameter_mm',
  'Диаметр (D), мм': 'diameter_mm',
  'Диаметр (см)': 'diameter_cm',
  'Диаметр мм': 'diameter_mm',
  'Диаметр плафона верхний, мм': 'shade_top_diameter_mm',
  'Диаметр плафона нижний, мм': 'shade_bottom_diameter_mm',
  'Диаметр потолочной чаши': 'ceiling_cup_diameter',
  'Диаметр потолочной чаши, мм': 'ceiling_cup_diameter_mm',
  'Диаметр потолочной чаши мм': 'ceiling_cup_diameter_mm',
  'Диаметр потолочной чаши/крепления, мм': 'mounting_diameter_mm',
  'Диаметр врезного отверстия': 'cutout_diameter',
  'Диаметр врезного отверстия, мм': 'cutout_diameter_mm',
  'Диаметр драйвера': 'driver_diameter',
  'Диаметр монтажного отверстия': 'mounting_hole_diameter',
  'Диаметр основания (отверстия встройки) (d), мм': 'base_diameter_mm',
  'Глубина (высота) основания (отверстия встройки) (h), мм': 'recessed_depth_mm',
  'Глубина (см)': 'depth_cm',
  'Глубина врезного отверстия': 'cutout_depth',
  'Глубина врезного отверстия, мм': 'cutout_depth_mm',
  'Глубина встройки, мм': 'recessed_depth_mm',
  'Глубина макс, мм': 'depth_max_mm',
  'Глубина монтажного отверстия': 'mounting_hole_depth',
  'Глубина, мм': 'depth_mm',
  'Вес': 'weight',
  'Вес(брутто)': 'weight_gross',
  'Вес брутто': 'weight_gross',
  'Bес упаковки, кг': 'weight_gross_kg',
  'Вес без упаковки': 'weight_netto',
  'Вес нетто': 'weight_netto',
  'Вес с упаковкой': 'weight_with_packaging',
  'Вес светильника в кг': 'weight_kg',
  'Вес кг': 'weight_kg',
  'Брутто': 'weight_gross',
  'Высота коробки': 'box_height',
  'Высота коробки см': 'box_height_cm',
  'Высота брутто, см': 'box_height_cm',
  'Высота упаковки мм': 'packaging_height_mm',
  'Высота (упаковки), см': 'packaging_height_cm',
  'Длина коробки': 'box_length',
  'Длина коробки см': 'box_length_cm',
  'Длина брутто, см': 'box_length_cm',
  'Длина коробки, см': 'box_length_cm',
  'Длина упаковки мм': 'packaging_length_mm',
  'Длина (упаковки), см': 'packaging_length_cm',
  'Ширина коробки': 'box_width',
  'Ширина коробки см': 'box_width_cm',
  'Ширина брутто, см': 'box_width_cm',
  'Ширина (упаковки), см': 'packaging_width_cm',
  'Ширина упаковки мм': 'packaging_width_mm',
  'Габариты упаковки, см': 'packaging_dimensions_cm',
  'Oбъем упаковки, м3': 'packaging_volume_m3',
  'Тип цоколя': 'base_type',
  'Цоколь': 'base_type',
  'Количество ламп': 'lamp_count',
  'Количество плафонов': 'lamp_count',
  'Мощность лампы, W': 'lamp_power_w',
  'Мощность': 'power_w',
  'Общая мощность, W': 'total_power_w',
  'Мощность, Вт': 'power_w',
  'Тип лампы': 'lamp_type',
  'Тип лампочки (основной)': 'lamp_type',
  'Лампы в комплекте': 'lamps_included',
  'Встроенные светодиоды': 'built_in_led',
  'LED': 'led',
  'Источник света': 'light_source',
  'Альтернативные лампы': 'alternative_lamps',
  'Световой поток': 'luminous_flux',
  'Световой поток, lm': 'luminous_flux_lm',
  'Световой поток, Lm': 'luminous_flux_lm',
  'Цветовая температура': 'color_temperature',
  'Индекс цветопередачи': 'cri_index',
  'Индекс цветопередачи (Ra)': 'cri_index',
  'Индекс цветопередачи CRI, Ra': 'cri_index',
  'Площадь освещения, м2': 'lighting_area_m2',
  'Допустимая площадь освещения': 'lighting_area',
  'Напряжение': 'voltage',
  'Напряжение, V': 'voltage',
  'Класс электробезопасности': 'safety_class',
  'Частота сети': 'mains_frequency',
  'Пылевлагозащита, IP': 'ip_rating',
  'Степень пылевлагозащиты IP': 'ip_rating',
  'Степень защиты, IP': 'ip_rating',
  'Защита IP': 'ip_rating',
  'Степень пылевлагозащиты': 'ip_rating',
  'Степень защиты': 'protection_rating',
  'IP (пылевлагозащита)': 'ip_rating',
  'Диапазон рабочих температур': 'operating_temperature',
  'Диапазон рабочей температуры C': 'operating_temperature',
  'Пульт': 'remote_control',
  'Пульт ДУ': 'remote_control',
  'Диммирование': 'dimmable',
  'Диммер': 'dimmable',
  'Диммируемость': 'dimmable',
  'Диммируемые': 'dimmable',
  'Регулятор яркости Диммер': 'dimmable',
  'Выключатель': 'switch',
  'Выключатель или диммер на корпусе': 'switch_on_body',
  'Выключатель сенсорный': 'touch_switch',
  'Touch сенсор': 'touch_sensor',
  'Датчик движения': 'motion_sensor',
  'Датчик освещенности (день-ночь)': 'day_night_sensor',
  'Управление через приложение': 'app_control',
  'Крепление': 'mounting_type',
  'Способ монтажа': 'mounting_method',
  'Тип крепления светильника': 'mounting_fixture_type',
  'Место монтажа': 'mounting_location',
  'Крепеж': 'fastening_type',
  'Врезной диаметр': 'recessed_diameter',
  'Интерьер': 'interior',
  'Интерьеры': 'interiors',
  'Назначение': 'purpose',
  'Вид': 'product_type',
  'Вид светильника': 'fixture_type',
  'Тип светильника': 'fixture_type',
  'Зона размещения': 'placement_zone',
  'Форма плафона': 'shade_shape',
  'Вид рассеивателя': 'diffuser_type',
  'Абажур': 'lampshade',
  'Абажур/плафон': 'lampshade',
  'Форма': 'shape',
  'Гарантия': 'warranty',
  'Гарантийный срок': 'warranty_period',
  'Гарантия производителя': 'warranty_manufacturer',
  'Гарантия месяцы': 'warranty_months',
  'Страна бренда': 'brand_country',
  'Страна': 'country',
  'Артикул': 'vendor_code',
  'Штрихкод': 'barcode',
  'Возможность замены ламп': 'lamp_replaceable',
  'Возможность окрашивания светильника': 'paintable',
  'Дополнительные сведения': 'additional_info',
  'Дополнительная подсветка': 'additional_lighting',
  'Доп. источник света, Комплектация доп лампами': 'additional_light_source',
  'Дополнительный источник света, Количество доп ламп': 'additional_lamp_count',
  'Дополнительный источник света, Мощность, W': 'additional_lamp_power',
  'Дополнительный источник света, тип цоколя': 'additional_lamp_base',
  'Аксессуары': 'accessories',
  '3D модель': 'model_3d',
  'Наличие поворотного механизма': 'swivel_mechanism',
  'Изменение цветовой температуры': 'color_temp_adjustable',
  'Shema': 'schema',
  'Схема': 'schema',
  'Блок питания (драйвер/трансфоматор)': 'power_supply',
  'Длина провода': 'cable_length',
  'Длина провода, мм': 'cable_length_mm',
  'Длина провода/цепи, м': 'cable_or_chain_length_m',
  'Длина цепи': 'chain_length',
  'Длина цепи или шнура см Длина цепи': 'chain_length_cm',
  'Выходное напряжение драйвера, макс': 'driver_output_voltage_max',
  'Выходное напряжение драйвера, мин': 'driver_output_voltage_min',
  'Выходная сила тока на канал, мА': 'driver_output_current_ma',
  'Длина драйвера': 'driver_length',
  'Выходное напряжение, В': 'output_voltage',
  'Max длина низковольтной линии (светодиодной ленты), м': 'max_low_voltage_line_length',
  'Длина врезного отверстия': 'cutout_length',
  'Длина врезного отверстия, мм': 'cutout_length_mm',
  'Длина основания (отверстия встройки) (l), мм': 'base_length_mm',
  'Диаметр отверстия встройки min-max (d), мм': 'cutout_diameter_min_max_mm',
  'Высота полоточной чаши': 'ceiling_cup_height',
  'Длина потолочной чаши': 'ceiling_cup_length',
  'Длина потолочной чаши, мм': 'ceiling_cup_length_mm',
  'Длина потолочной чаши/крепления, мм': 'mounting_length_mm',
  'Возможность использования универсальных креплений': 'universal_mounting',
  'DIP-переключатель': 'dip_switch',
  'UGR (Unified Glare Rating) Показатель дискомфорта или слепимости. Ниже - лучше': 'ugr_rating',
  'Дизайнерам': 'designers',
  'Каталог': 'catalog_info',
  'Дата поступления': 'availability_date',
  'Минимальный остаток': 'min_stock',
  'Срок службы': 'service_life',
  'Срок службы, LED': 'led_service_life',
  'Коэффициент пульсации': 'flicker_coefficient',
  'Время автономной работы до , ч': 'autonomous_operation_time',
  'Бренд': 'brand',
  'Пульт дистанционного управления': 'remote_control_included',
  'Регулировка по высоте': 'height_adjustable',
  'Тип монтажа': 'mounting_type_detail',
  'Напряжение питания, В': 'supply_voltage',
  'Напряжение питания В': 'supply_voltage',
  'Места применения': 'application_areas',
  'Суммарная мощность LED, Вт': 'total_led_power_w',
  'Потребляемое количество ватт Мощность': 'consumed_power_w',
  'Мощность Вт': 'power_w',
  'Масса Брутто кг': 'weight_gross_kg',
  'Масса, кг': 'weight_kg',
  'Масса нетто кг': 'weight_netto_kg',
  'Объемы упаковки м3': 'packaging_volume_m3',
  'Общая мощность Вт': 'total_power_w',
  'Цвет арматуры/тип': 'frame_color_type',
  'Подходит для натяжных потолков': 'stretch_ceiling_compatible',
  'Площадь освещения': 'lighting_area',
  'Материал основания': 'base_material',
  'Место размещения': 'placement_location',
  'Количество плафонов, шт.': 'lamp_count',
  'Количество патронов': 'socket_count',
  'Направление плафона': 'shade_direction',
  'Патрон': 'socket_type',
  'Рекомендуемый тип лампы': 'recommended_lamp_type',
  'Потребляемая мощность': 'consumed_power',
  'Диаметр плафона': 'shade_diameter',
  'Высота светильника': 'fixture_height',
  'Высота плафона': 'shade_height',
  'Высота min': 'height_min',
  'Высота max': 'height_max',
  'Поверхность монтажа': 'mounting_surface',
  'Тип поверхности монтажа': 'mounting_surface_type',
  'Способ крепления': 'fastening_method',
  'Вид крепления к потолку': 'ceiling_attachment_type',
  'Тип управления': 'control_type',
  'Количество режимов': 'mode_count',
  'Угол рассеивания': 'beam_angle',
  'Количество светодиодов': 'led_count',
  'Световая отдача': 'luminous_efficacy',
  'Минимальная высота помещения': 'min_room_height',
  'Способ подключения': 'connection_method',
  'Тип драйвера': 'driver_type',
  'Мощность драйвера': 'driver_power',
  'Количество контуров': 'circuit_count',
  'Расстояние между креплениями': 'mounting_spacing',
  'Тип рассеивателя': 'diffuser_type_detail',
  'Световой поток LED': 'led_luminous_flux',
  'Тип плафона': 'shade_type',
  'Диаметр основания': 'base_diameter',
  'Тип корпуса': 'body_type',
  'Материал крепления': 'fastening_material',
  'Форма основания': 'base_shape',
  'Тип пускорегулирующего аппарата': 'ballast_type',
  'Класс защиты от поражения электрическим током': 'electric_shock_protection_class',
  'Тип цоколя доп.': 'additional_base_type',
  'Длина троса': 'cable_length',
  'Тип крепления': 'attachment_type',
  'Тип товара': 'product_type',
  'Особенности': 'features',
  'Комплектация': 'complectation',
  'Материал провода': 'cable_material',
  'Высота подвеса': 'suspension_height',
  'Количество рожков': 'arm_count',
  'Тип выключателя': 'switch_type',
  'Мощность LED всего, W': 'total_led_power_w',
  'Мощность LED всего': 'total_led_power',
  'Напряжение драйвера': 'driver_voltage',
  'Сила тока драйвера': 'driver_current',
  'Высота в сборе min-max, мм': 'assembled_height_min_max_mm',
  'Кол-во точек света': 'light_point_count',
  'Размер основания': 'base_size',
  'Материал абажура': 'lampshade_material',
  'Цвет абажура': 'lampshade_color',
  'Тип поверхности': 'surface_type',
  'Материал декоративных элементов': 'decorative_elements_material',
  'Высота от пола': 'floor_height',
  'Высота от потолка': 'ceiling_height',
  'Длина шнура': 'cord_length',
  'Материал подвески': 'suspension_material',
  'Форма плафона/абажура': 'shade_shape',
  'Тип конструкции': 'construction_type',
  'Количество рожков/плафонов': 'arm_shade_count',
  'Диаметр основания, мм': 'base_diameter_mm',
  'Материал арматуры/основания': 'frame_base_material',
  'Цвет арматуры/основания': 'frame_base_color',
  'Высота без цепи': 'height_without_chain',
  'Материал цепи': 'chain_material',
  'Тип подвески': 'suspension_type',
  'Форма основания/крепления': 'base_shape',
  'Материал плафонов/абажуров': 'shade_lampshade_material',
  'Количество ярусов': 'tier_count',
  'Форма люстры': 'chandelier_shape',
  'Тип стекла': 'glass_type',
  'Тип кристалла': 'crystal_type',
  'Цветовая температура, К': 'color_temperature_k',
  'Мощность LED, Вт': 'led_power_w',
  'Световой поток, Лм': 'luminous_flux_lm',
  'Количество светодиодов, шт': 'led_count_pcs',
  'Высота min, мм': 'height_min_mm',
  'Высота max, мм': 'height_max_mm',
  'Диаметр плафона, мм': 'shade_diameter_mm',
  'Высота плафона, см': 'shade_height_cm',
  'Диаметр плафона, см': 'shade_diameter_cm',
  'Длина в сложенном виде': 'folded_length',
  'Тип складного механизма': 'folding_mechanism_type',
  'Материал ножек': 'leg_material',
  'Количество ножек': 'leg_count',
  'Тип лампы (основной)': 'lamp_type_main',
  'Мощность лампы (основной), W': 'lamp_power_main_w',
  'Цоколь (основной)': 'base_type_main',
  'Тип лампы (доп), Кол-во': 'lamp_type_additional_count',
  'Мощность лампы (доп), W': 'lamp_power_additional_w',
  'Цоколь (доп)': 'base_type_additional',
}
