// Auto-generated seed file for Sonex
// Products: 17

import { SeedProductDefinition } from './seedTypes'

export function getSonexProducts(): SeedProductDefinition[] {
  return [
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Geta Silver 2076/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-geta-silve-2076/DL',
      description: '',
      price: 120.87,
      compareAtPrice: 201.38,
      stock: 100,
      sku: '2076/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Geta Silver 2076/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Geta Silver 2076/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_bd421a7ea7f59fc3ec42543862853e95.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Geta Silver' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Серебро' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Хай-тек' }, { key: 'Интерьер', value: 'Для прихожей' }, { key: 'Количество ламп', value: 1 }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }, { key: 'Световой поток, lm', value: 2790 }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Geta Coffee 2075/EL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-geta-coffe-2075/EL',
      description: '',
      price: 159.81,
      compareAtPrice: 266.25,
      stock: 100,
      sku: '2075/EL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Geta Coffee 2075/EL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Geta Coffee 2075/EL',
      images: [{ path: '/Sonex/Sonex-1_files/small_809615d6ab4a1da18ffbff3e147334d6.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Geta Coffee' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Коричневый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Хай-тек' }, { key: 'Интерьер', value: 'Для спальни' }, { key: 'Количество ламп', value: 1 }, { key: 'Мощность лампы, W', value: 72 }, { key: 'Общая мощность, W', value: 72 }, { key: 'Тип цоколя', value: 'LED' }, { key: 'Световой поток, lm', value: 3612 }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Geta Coffee 2075/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-geta-coffe-2075/DL',
      description: '',
      price: 120.87,
      compareAtPrice: 201.38,
      stock: 100,
      sku: '2075/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Geta Coffee 2075/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Geta Coffee 2075/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_61c233952f8cd96aa723141c7efe952b.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Geta Coffee' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Коричневый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Хай-тек' }, { key: 'Интерьер', value: 'Для прихожей' }, { key: 'Количество ламп', value: 1 }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }, { key: 'Световой поток, lm', value: 2790 }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Lazana 2074/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-lazana-207-2074/DL',
      description: '',
      price: 67.12,
      compareAtPrice: 111.83,
      stock: 100,
      sku: '2074/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Lazana 2074/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Lazana 2074/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_284fb52ccf0f4b9a9890d3d48cf419c5.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Lazana' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Хром' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Модерн' }, { key: 'Интерьер', value: 'Для спальни' }, { key: 'Количество ламп', value: 1 }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }, { key: 'Световой поток, lm', value: 2790 }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Prisa 2057/EL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-s-pultom-du-sone-2057/EL',
      description: '',
      price: 178.72,
      compareAtPrice: 297.75,
      stock: 100,
      sku: '2057/EL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Prisa 2057/EL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Prisa 2057/EL',
      images: [{ path: '/Sonex/Sonex-1_files/small_7fd0dd89af96a9e3127889b213866910.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Prisa' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Современный' }, { key: 'Интерьер', value: 'Для офиса' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 72 }, { key: 'Общая мощность, W', value: 72 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Abasi 2052/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-abasi-2052-2052/DL',
      description: '',
      price: 61.88,
      compareAtPrice: 103.09,
      stock: 100,
      sku: '2052/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Abasi 2052/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Abasi 2052/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_8c8cc45b7320f7cb16cbb00d122d0ec8.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Abasi' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Современный' }, { key: 'Интерьер', value: 'Для ванной' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }, { key: 'Световой поток, lm', value: 3400 }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Leka 2051/EL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-s-pultom-du-sone-2051/EL',
      description: '',
      price: 57.06,
      compareAtPrice: 95.06,
      stock: 100,
      sku: '2051/EL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Leka 2051/EL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Leka 2051/EL',
      images: [{ path: '/Sonex/Sonex-1_files/small_a2ad1cd5041b8113aa5b8133e01eb714.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Leka' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Современный' }, { key: 'Интерьер', value: 'Для офиса' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 72 }, { key: 'Общая мощность, W', value: 72 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Leka 2051/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-leka-2051--2051/DL',
      description: '',
      price: 34.75,
      compareAtPrice: 57.90,
      stock: 100,
      sku: '2051/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Leka 2051/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Leka 2051/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_c577c83117227bc9769d4398c5594e93.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Leka' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Современный' }, { key: 'Интерьер', value: 'Для офиса' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }, { key: 'Световой поток, lm', value: 3400 }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Kabrio 2049/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-s-pultom-du-sone-2049/DL',
      description: '',
      price: 72.57,
      compareAtPrice: 120.90,
      stock: 100,
      sku: '2049/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Kabrio 2049/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Kabrio 2049/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_368aa218deacf4e423a5315715333612.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Kabrio' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Современный' }, { key: 'Интерьер', value: 'Для офиса' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Visma 2048/EL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-visma-2048-2048/EL',
      description: '',
      price: 177.60,
      compareAtPrice: 295.88,
      stock: 100,
      sku: '2048/EL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Visma 2048/EL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Visma 2048/EL',
      images: [{ path: '/Sonex/Sonex-1_files/small_ec7dbe390dfd05c82b316bd573106c73.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Visma' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Модерн' }, { key: 'Интерьер', value: 'Для гостиной' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 72 }, { key: 'Общая мощность, W', value: 72 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Visma 2048/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-visma-2048-2048/DL',
      description: '',
      price: 45.31,
      compareAtPrice: 75.49,
      stock: 100,
      sku: '2048/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Visma 2048/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Visma 2048/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_e692581cc137f35ae3f4c8f9092a5ea7.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Visma' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Модерн' }, { key: 'Интерьер', value: 'Для ванной' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник Sonex Gino 2045/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-sonex-gino-2045--2045/DL',
      description: '',
      price: 110.97,
      compareAtPrice: 184.88,
      stock: 100,
      sku: '2045/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник Sonex Gino 2045/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник Sonex Gino 2045/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_99df08a3f17d28d33a7487d76c00b70d.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Gino' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Современный' }, { key: 'Интерьер', value: 'Для офиса' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }, { key: 'Световой поток, lm', value: 3400 }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Floors 2041/EL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-s-pultom-du-sone-2041/EL',
      description: '',
      price: 118.24,
      compareAtPrice: 196.99,
      stock: 100,
      sku: '2041/EL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Floors 2041/EL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Floors 2041/EL',
      images: [{ path: '/Sonex/Sonex-1_files/small_b473d51fb43ec64ee796ac82071fddee.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Floors' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Прованс' }, { key: 'Интерьер', value: 'Для спальни' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 72 }, { key: 'Общая мощность, W', value: 72 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Floors 2041/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-s-pultom-du-sone-2041/DL',
      description: '',
      price: 84.03,
      compareAtPrice: 139.99,
      stock: 100,
      sku: '2041/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Floors 2041/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Floors 2041/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_9599bdab29c403b39cf3df8634b11b63.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Floors' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Прованс' }, { key: 'Интерьер', value: 'Для спальни' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Wave 2040/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-s-pultom-du-sone-2040/DL',
      description: '',
      price: 121.55,
      compareAtPrice: 202.50,
      stock: 100,
      sku: '2040/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Wave 2040/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Wave 2040/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_3e4f6dea564f9b7f87c72c07fd3f761e.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Wave' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Современный' }, { key: 'Интерьер', value: 'Для спальни' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Stone 2039/DL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-s-pultom-du-sone-2039/DL',
      description: '',
      price: 126.21,
      compareAtPrice: 210.26,
      stock: 100,
      sku: '2039/DL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Stone 2039/DL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Stone 2039/DL',
      images: [{ path: '/Sonex/Sonex-1_files/small_4402ce239b538d30a6f5326406d68fee.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Stone' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Овал' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Современный' }, { key: 'Интерьер', value: 'Для офиса' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 48 }, { key: 'Общая мощность, W', value: 48 }, { key: 'Тип цоколя', value: 'LED' }],
    },
    {
      name: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Brisa 2036/EL',
      slug: 'nastenno-potolochnyj-svetodiodnyj-svetilnik-s-pultom-du-sone-2036/EL',
      description: '',
      price: 120.45,
      compareAtPrice: 200.66,
      stock: 100,
      sku: '2036/EL',
      categorySlug: 'potolochnye-svetilniki',
      brand: 'Sonex',
      brandCountry: 'Польша',
      badges: [],
      rating: 4.5,
      reviewsCount: 0,
      metaTitle: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Brisa 2036/EL — купить в Аура Света',
      metaDesc: 'Настенно-потолочный светодиодный светильник с пультом ДУ Sonex Brisa 2036/EL',
      images: [{ path: '/Sonex/Sonex-1_files/small_7c9d7844a96746d76cf7d126bbfc3e5d.jpeg', isMain: true }],
      propertyValues: [{ key: 'Коллекция', value: 'Brisa' }, { key: 'Тип светильника', value: 'Настенно-потолочные' }, { key: 'Цвет', value: 'Белый' }, { key: 'Цвет плафонов', value: 'Белый' }, { key: 'Цвет арматуры', value: 'Белый' }, { key: 'Форма плафона', value: 'Круглый' }, { key: 'Материал плафонов', value: 'Пластик' }, { key: 'Материал арматуры', value: 'Металл' }, { key: 'Стиль', value: 'Модерн' }, { key: 'Интерьер', value: 'Для гостиной' }, { key: 'Количество ламп', value: 1 }, { key: 'Лампы в комплекте', value: true }, { key: 'Мощность лампы, W', value: 72 }, { key: 'Общая мощность, W', value: 72 }, { key: 'Тип цоколя', value: 'LED' }],
    },
  ]
}
