import type { Metadata } from 'next'
import './globals.css'
import MobileHeader from '@/widgets/header/ui/MobileHeader'
import MobileBottomNav from '@/widgets/navigation/ui/MobileBottomNav'
import { TRPCProvider } from '@/lib/trpc/client'
import { trpc, HydrateClient } from '@/lib/trpc/server'

export const metadata: Metadata = {
	title: 'Интернет-магазин люстр и светильников в Мозыре - Аура света',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	// Prefetch categories for navigation components (CategoryNav, MobileCatalogMenu)
	void trpc.categories.getNav.prefetch()

	return (
		<html lang='ru'>
			<body className='font-sans antialiased'>
				<TRPCProvider>
					<HydrateClient>
						<MobileHeader />
						{children}
						<MobileBottomNav />
					</HydrateClient>
				</TRPCProvider>
			</body>
		</html>
	)
}
