import type { Metadata } from 'next'
import './globals.css'
import MobileHeader from '@/components/layout/MobileHeader'
import MobileBottomNav from '@/components/layout/MobileBottomNav'

export const metadata: Metadata = {
	title: 'Интернет-магазин люстр и светильников в Мозыре - Аура света',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className='font-sans antialiased'>
				<MobileHeader />
				{children}
				<MobileBottomNav />
			</body>
		</html>
	)
}
